### ISSUE TITLE
add callback restart

### ISSUE THREAD

**Issue by ltdeta** [o3bvv/jQuery-backward-timer#1]
how can i restart the timer after callback is called?
example:
Start: 10sec -> End: 0sec -> callback((a)synchronously) -> Start: 10sec. ...

**Comment by o3bvv** [comment]
You can reset timer and start it again inside `on_exhausted`: http://jsfiddle.net/oblalex/jdL1db55/

Note: in this example you will not see `0:00:00` rendered, because timer is restarted immediately. Seems to be valid. Tell me, what do you think about it.

**Comment by ltdeta** [comment]
thanks

**Comment by o3bvv** [comment]
Can I close the issue?

**Comment by ltdeta** [comment]
yes
