### ISSUE TITLE
timer update intervall

### ISSUE THREAD

**Issue by ltdeta** [o3bvv/jQuery-backward-timer#2]
At the moment the timer will updated each second.
adding a new option for a refresh frequence like 5sec 10sec etc.

**Comment by o3bvv** [comment]
Seems to be a useful option. I think I'll implement it today a bit later.

**Comment by o3bvv** [comment]
Try this out: http://oblalex.github.io/jQuery-backward-timer/#how-to-set-timer-s-step

**Comment by ltdeta** [comment]
Perfect !
