### ISSUE TITLE
not working on input-element

### ISSUE THREAD

**Issue by ltdeta** [o3bvv/jQuery-backward-timer#4]
old:
plugin.target.val(value)

new:
if (plugin.target.is("input"))
  plugin.target.val(value)
else
  plugin.target.text(value)

**Comment by o3bvv** [comment]
What is `old` and what is `new`?

**Comment by ltdeta** [comment]
old means it is the original code ;)
"new" is my suggestion

**Comment by o3bvv** [comment]
Well, actually, original is `plugin.target.text(value)`: http://bit.ly/1DGFJ8V

This issue can be a bit complicated, if it is supposed to be done in a proper way. There are many ways to set value: we can pass it directly to a `text/html/val` method or to an `attr/prop/data` method enclosed with attribute name.

Nevertheless, from pragmatic point of view, your suggestion seems to be quite OK. If the paragraph above is not a big deal, we can apply your suggestion. Please, tell me what you think about it.

**Comment by ltdeta** [comment]
I would prefer  the "text/html/val" method it is closer to native javascript ;)
