### ISSUE TITLE
counter not updated - callback with ajax call 

### ISSUE THREAD

**Issue by ltdeta** [o3bvv/jQuery-backward-timer#5]
then the callback event is triggert i call a sync ajax request
the timer is not updated by "0" bevor the ajax request was send

![example](https://cloud.githubusercontent.com/assets/1563652/5455151/4d8f38e6-8539-11e4-9c30-d9e9555826a6.jpg)

do you have any idea?

**Comment by o3bvv** [comment]
investigating… :shipit:

**Comment by o3bvv** [comment]
Hm… Sorry, I cannot reproduce this. Are we talking about this case http://jsfiddle.net/7b7accua/1/ ?

**Comment by ltdeta** [comment]
Yes , but i use Ajax with "async:false"

**Comment by ltdeta** [comment]
and loading a  lot of data from sql-server for a few seconds

**Comment by o3bvv** [comment]
Well, this is an example with `async: false`: http://jsfiddle.net/7b7accua/2/
Seems to be still valid.

**Comment by ltdeta** [comment]
After calling the request (sql statment execution for several seconds) the timer freeze
 i have just described on top

**Comment by o3bvv** [comment]
Sorry, I really tried to understand this, but I don't get it :confused:. There's no obvious reason for such behaviour.

Please, show how do you use this plugin. It would be better if you provide jsfiddle or something like that. And it woud be really nice if you'll try to debug source javascript, it's really small.

Thanks.

**Comment by ltdeta** [comment]
Ok
