### ISSUE TITLE
Don't stop counter at zero

### ISSUE THREAD

**Issue by svinkle** [o3bvv/jQuery-backward-timer#6]
Hi,

Would it be possible to keep the timer going in to negative numbers? There doesn't seem to be an option for this or a way to start a timer at 0 and continue counting down.

Thanks!

**Comment by o3bvv** [comment]
Hi!

Well, this sounds really strange, but it's possible anyway.

I'll take this in progress today or tomorrow.

**Comment by svinkle** [comment]
Yes, it's a strange use case, but a requirement I need to fulfill. 

Thank you very much!

**Comment by o3bvv** [comment]
@svinkle: Is this what you mean? http://git.io/AkwY

If yes, please, tell me why do you really need this.

**Comment by svinkle** [comment]
Yep, this is exactly what I needed. Thanks!

We have a survey type app that uses your countdown. We want to see how long the survey takes, given a set amount of time. Even if the user goes overtime we still like to know how much overtime they've gone. That's pretty much it.

Thanks again!

**Comment by o3bvv** [comment]
Okay, now I see.

IMHO, maybe, it would be better to use bidirectional timer and start counting upward after backward timer is exhausted. And apply some style or append some message near upward timer.

Anyway, I'm glad you are happy. Can we close the issue?

**Comment by svinkle** [comment]
Closing. Thanks again!
