### ISSUE TITLE
request - new event cancel

### ISSUE THREAD

**Issue by ltdeta** [o3bvv/jQuery-backward-timer#7]
i want to do some action if a timer was cancelled
can you insert a cancel event please?

**Comment by o3bvv** [comment]
Yes, I think it can be ready tonight or so.

p.s. Why do you can not invoke your action in place you cancel timer?

**Comment by ltdeta** [comment]
i have some positions where i need to cancel und cleanup some other things
make it easier for me handling this inside the timer :)

PS: added a [pull request](https://github.com/oblalex/jQuery-backward-timer/pull/8)

**Comment by o3bvv** [comment]
Closed via #9.
